name: Build and publish Docker image
on:
  push:
    branches:  main
jobs:
  push_to_registry:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          tags: ghcr.io/emar10/hqbot:${{ github.sha }},ghcr.io/emar10/hqbot:latest
